site_name: Evergreen
site_description: Efficient Claim Verification for Semantic Aggregates
site_url: http://127.0.0.1:8000/

nav:
  - index.md
  - API Reference for LLMs: api_for_llms.md

theme:
  name: material
  palette:
    scheme: slate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_root_heading: true
            show_source: false
            show_signature_annotations: true
            separate_signature: true
  - llmstxt:
      full_output: llms-full.txt
      sections:
        API Reference for LLMs:
          - api_for_llms.md