from __future__ import annotations

import ast
import re
import time
from dataclasses import dataclass
from enum import Enum

import evergreen as evg
from evergreen.catalog.schema import Schema
from evergreen.data_frame import DataFrame
from evergreen.model.language_model import LanguageModel, LanguageModelMetrics

COMPILE_CLAIM_PROMPT_TEMPLATE = """<instructions>
You are an agent who is an expert in logic, data analysis, and databases.
You are given a natural language <claim>, which was generated by semantically
aggregating over a dataset with the provided <agg_prompt> to an LLM.
The provided <schema> describes the fields of the underlying data.
Your task is to compile the <claim> into a semantic verification query.
The semantic verification query will be executed to verify the <claim>.

Think step by step and output your reasoning for each step below:
1. Formally express the logical structure of the <claim>.
  - Leverage your knowledge of first-order logic and its extensions here.
  - Identify the key logical components of the <claim>, such as
    constants, variables, predicates, functions, quantifiers, etc.
  - If negation is present, rewrite the <claim> in negation normal form (NNF) by
    using De Morgan's laws to push negation inwards such that they only apply to
    atomic predicates. You must use rewritten <claim> in NNF instead of the original
    <claim> in the following steps for constructing the semantic verification query.
  - If provided, use the <hints> below for clarification.
2. Based on the provided <api_reference> and <schema>,
   precisely identify the query operators and expressions to represent the <claim>.
   Think very carefully about the underlying data specified by the <schema> and
   how it should inform your choice of query operators and expressions.
   Below are some tips on how to use operators to express the <claim>:
   - `filter()` can be used to select relevant tuples that define the <claim>'s scope.
     Importantly, when a <claim> is about a specific topic, select tuples that
     mention that topic before computing aggregates. However, do not add filters that
     merely restate the dataset's existing scope (e.g., that the tuples concern a
     particular entity or domain already implied by the <agg_prompt> or <schema>);
     the data is already scoped, so only filter to a meaningful sub-population that
     the <claim> itself restricts attention to. When the <claim> or <hints> express a
     quantity relative to a sub-population, `filter()` to that sub-population first so
     it forms the base (denominator) of the subsequent aggregate.
   - `map()` can be used to label tuples with extracted features. To count tuples or
     compute the proportion of tuples that exhibit a *semantic* feature, label the
     feature as an explicit boolean column with `map(prompt(..., bool))` and then
     aggregate that column with `count_if()` or `proportion()`. Do not instead
     `filter()` on the feature and count the surviving tuples (e.g.,
     `count_if(lit(True))`); the semantic feature must be its own column. When a tuple
     should be counted only if it satisfies several conditions at once, fold those
     conditions into a single `map(prompt(..., bool))` rather than chaining a
     `filter()` and a `map()`. For a categorical feature with more than two possible
     values, map it to its own `Enum` column with `map(prompt(..., SomeEnum))` and
     derive the needed booleans inline via comparisons (e.g.,
     `col("c").eq(SomeEnum.X)`). In contrast, a predicate that is purely a
     comparison over an existing column (e.g., a count or proportion threshold)
     should be written inline inside the aggregate (e.g., `count_if(col("c") >= k)`)
     rather than materialized with an intermediate `map()`.
   - `aggregate()` can be used to compute quantities with optional grouping.
     Use `group_by` when the <claim> involves computing quantities across groups.
     When the <claim>'s language maps to well-defined (generalized) quantifiers,
     use them precisely. However, when the <claim>'s language maps to vague quantifiers,
     err on the side of leniency, but ensure thresholds remain meaningful.
   - `with_rank()` can be used to rank groups according to computed quantities.
     This ranking can be used for comparisons between groups.
   - `check()` can be used to verify the final predicate.
   When writing the `prompt()` text for a `filter()` or `map()`, do not reference the
   dataset's specific entity name (e.g., a particular business, product, or person);
   that name is already implied by the <agg_prompt> and <schema>. You may, however,
   refer to the generic entity type or scope (e.g., "the business") when it
   makes the feature being extracted clearer.
3. Output the semantic verification query.
   - You can assume that a DataFrame is available with the name `df`.
   - `df` already has the specified schema.
   - The last operator in the query should be a `check()` operator.
   - You can define `Enum` classes to represent the possible values of a new column.
   - Output the query in a ```python``` code block.
   - If the API cannot sufficiently express the <claim>, leave the code block empty.
   - Do NOT include import statements (e.g., `Enum`), variable assignments,
     or comments in the code.
   - You may output multiple queries to explore different approaches;
     however, the last code block will be considered as your final answer.
</instructions>

<api_reference>
{api_reference}
</api_reference>

<agg_prompt>
{agg_prompt}
</agg_prompt>

<schema>
{schema}
</schema>

<claim>
{claim}
</claim>

<hints>
{hints}
</hints>"""


class ClaimCompiler:
    _API_REFERENCE_PATH = "site/llms-full.txt"
    _PATTERN = r"```(?:python)?\s*(.*?)\s*```"

    def __init__(self, language_model: LanguageModel) -> None:
        self._language_model = language_model

        with open(self._API_REFERENCE_PATH) as f:
            self._api_reference = f.read()

    def compile(
        self, agg_prompt: str, schema: Schema, claim: str, hints: str
    ) -> ClaimCompilationResult:
        t0 = time.perf_counter()

        prompt = COMPILE_CLAIM_PROMPT_TEMPLATE.format(
            api_reference=self._api_reference,
            agg_prompt=agg_prompt,
            schema=schema,
            claim=claim,
            hints=hints,
        )

        response = self._language_model.prompt_without_schema(prompt)

        matches = re.findall(self._PATTERN, response, re.DOTALL)
        query = matches[-1].strip() if matches else ""

        latency = time.perf_counter() - t0

        return ClaimCompilationResult(
            response, query, self._language_model.metrics(), latency
        )

    @staticmethod
    def build_query(df: DataFrame, query_src: str) -> DataFrame:
        namespace = {name: getattr(evg, name) for name in evg.__all__} | {
            "Enum": Enum,
            "df": df,
        }

        *setup, query = ast.parse(query_src).body
        assert isinstance(query, ast.Expr)

        exec(
            compile(ast.Module(body=setup, type_ignores=[]), "<query>", "exec"),
            namespace,
        )
        result_df = eval(
            compile(ast.Expression(body=query.value), "<query>", "eval"),
            namespace,
        )

        assert isinstance(result_df, DataFrame)
        return result_df


@dataclass(frozen=True)
class ClaimCompilationResult:
    response: str
    query: str
    language_model_metrics: tuple[LanguageModelMetrics, ...]
    latency: float

    def to_dict(self) -> dict[str, object]:
        return {
            "response": self.response,
            "query": self.query,
            "language_model_metrics": [
                metric.to_dict() for metric in self.language_model_metrics
            ],
            "latency": self.latency,
        }
