from __future__ import annotations

import re
import time
from dataclasses import dataclass

from evergreen.catalog.schema import Schema
from evergreen.model.language_model import LanguageModel, LanguageModelMetrics

COMPILE_CLAIM_PROMPT_TEMPLATE = """<instructions>
You are an agent who is an expert in logic, data analysis, and databases.
You are given a natural language <claim>, which was generated by semantically
aggreggating over a dataset with the provided <agg_prompt> to an LLM.
The provied <schema> indicates the fields that were used by the semantic
aggregation to generate the <claim>.
Your task is to compile the <claim> into a semantic verification query.
The semantic verification query will be executed to verify the <claim>.

Think step by step and output your reasoning for each step below:
1. Formally express the logical structure of the <claim>.
  - Leverage your knowledge of first-order logic and its extensions here.
  - Identify the key logical components of the <claim>, such as
    constants, variables, predicates, functions, quantifiers, etc.
  - If negation is present, rewrite the <claim> in negation normal form (NNF) by
    using De Morgan's laws to push negation inwards such that they only apply to
    atomic predicates. You must use rewritten <claim> in NNF instead of the original
    <claim> in the following steps for constructing the semantic verification query.
2. Based on the provided <api_reference> and <schema>,
   precisely identify the query operators and expressions to represent the <claim>.
   Think very carefully about the underlying data specified by the <schema> and
   how it should inform your choice of query operators and expressions.
   Below are some tips on how to use operators to express the <claim>:
   - `filter()` can be used to select relevant tuples that define the <claim>'s scope.
     Importantly, when a <claim> is about a specific topic, select tuples that
     mention that topic before computing aggregates.
   - `map()` can be used to label tuples with extracted features.
   - `aggregate()` can be used to compute quantities with optional grouping.
     Use `group_by` when the <claim> involves computing quantities across groups.
     When the <claim>'s language maps to well-defined (generalized) quantifiers,
     use them precisely. However, when the <claim>'s language maps to vague quantifiers,
     err on the side of leniency, but ensure thresholds remain meaningful.
   - `with_rank()` can be used to rank groups according to computed quantities.
     This ranking can be used for comparisons between groups.
   - `check()` can be used to verify the final predicate.
3. Output the semantic verification query.
   - You can assume that a DataFrame is available with the name `df`.
   - `df` already has the specified schema.
   - The last operator in the query should be a `check()` operator.
   - You can define `Enum` classes to represent the possible values of a new column.
   - Output the query in a ```python``` code block.
   - If the API cannot sufficiently express the <claim>, leave the code block empty.
   - Do NOT include import statements (e.g., `Enum`), variable assignments,
     or comments in the code.
   - You may output multiple queries to explore different approaches;
     however, the last code block will be considered as your final answer.
</instructions>

<api_reference>
{api_reference}
</api_reference>

<agg_prompt>
{agg_prompt}
</agg_prompt>

<schema>
{schema}
</schema>

<claim>
{claim}
</claim>"""


class ClaimCompiler:
    _API_REFERENCE_PATH = "site/llms-full.txt"
    _PATTERN = r"```(?:python)?\s*(.*?)\s*```"

    def __init__(self, language_model: LanguageModel) -> None:
        self._language_model = language_model

        with open(self._API_REFERENCE_PATH) as f:
            self._api_reference = f.read()

    def compile(
        self, agg_prompt: str, schema: Schema, claim: str
    ) -> ClaimCompilationResult:
        t0 = time.perf_counter()

        prompt = COMPILE_CLAIM_PROMPT_TEMPLATE.format(
            api_reference=self._api_reference,
            agg_prompt=agg_prompt,
            schema=schema,
            claim=claim,
        )

        response = self._language_model.prompt_without_schema(prompt)

        matches = re.findall(self._PATTERN, response, re.DOTALL)
        query = matches[-1].strip() if matches else ""

        latency = time.perf_counter() - t0

        return ClaimCompilationResult(
            response, query, self._language_model.metrics(), latency
        )


@dataclass(frozen=True)
class ClaimCompilationResult:
    response: str
    query: str
    language_model_metrics: tuple[LanguageModelMetrics, ...]
    latency: float

    def to_dict(self) -> dict[str, object]:
        return {
            "response": self.response,
            "query": self.query,
            "language_model_metrics": [
                metric.to_dict() for metric in self.language_model_metrics
            ],
            "latency": self.latency,
        }
